[package]
name = "ambergris"
version = "0.1.0"
authors = ["Redwarp <redwarp@gmail.com>"]
edition = "2021"
description = "Every journey must start somewhere."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
